name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go (${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build (${{ matrix.go }})
      run: go build ./...

    - name: Test (${{ matrix.go }})
      run: go test ./...
